Display information about subdomains.

diff --git a/0x10-https_ssl/0-world_wide_web b/0x10-https_ssl/0-world_wide_web
--- a/0x10-https_ssl/0-world_wide_web
+++ b/0x10-https_ssl/0-world_wide_web
@@ -1,19 +1,37 @@
 #!/usr/bin/env bash
-# Usage: ./1-world_wide_web <domain> <subdomain>
-# Display information about subdomains.
+# This script displays information about subdomains
 
-domain_information () {
-    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
-    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
+domain=$1
+subdomain=$2
+result=
+
+# print the information about the result returned
+print_domain_info() {
+    record_type=$(echo "$result" | awk '{print $4}')
+    ip_addr=$(echo "$result" | awk '{print $5}')
+    echo -n "The subdomain $subdomain is a $record_type record and points "
+    echo "to $ip_addr"
 }
 
-if [ "$#" == 1 ]
-then
-  domain_information "$1" "www"
-  domain_information "$1" "lb-01"
-  domain_information "$1" "web-01"
-  domain_information "$1" "web-02"
-elif [ "$#" == 2 ]
-then
-  domain_information "$1" "$2"
-fi
+# get information about the subdomains
+get_domain_info () {
+    if [[ $domain = "" ]]; then
+        echo "Domain name missing."
+        exit 1
+    fi
+    
+    if [[ $subdomain = "" ]]; then
+        known_sub_domains=("www" "lb-01" "web-01" "web-02")
+        for subdomain in "${known_sub_domains[@]}"; do
+            result=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION'\
+                    | tail -1)
+            print_domain_info
+        done
+        exit
+    fi
+
+    result=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION' | tail -1)
+    print_domain_info
+}
+
+get_domain_info
